spring:
  cloud:
    gateway:
      routes:
        - id: ms-productos
          uri: http://localhost:8082
          predicates:
            - Path=/api/productos/**
          filters:
            - AddResponseHeader=Access-Control-Allow-Origin, http://localhost:8085
            - AddResponseHeader=Access-Control-Allow-Methods, GET, POST, PUT, DELETE, OPTIONS
            - AddResponseHeader=Access-Control-Allow-Headers, Content-Type, Authorization
            - AddRequestHeader=Access-Control-Allow-Origin, http://localhost:8085

        - id: ms-usuarios
          uri: http://localhost:8081
          predicates:
            - Path=/api/permissions/**, /api/roles/**, /api/userroles/**, /api/rolespermisos/**, /api/usuarios/**
          filters:
            - AddResponseHeader=Access-Control-Allow-Origin, http://localhost:8085
            - AddResponseHeader=Access-Control-Allow-Methods, GET, POST, PUT, DELETE, OPTIONS
            - AddResponseHeader=Access-Control-Allow-Headers, Content-Type, Authorization
            - AddRequestHeader=Access-Control-Allow-Origin, http://localhost:8085

        - id: ms-categorias
          uri: http://localhost:8083
          predicates:
            - Path=/api/categorias/**
          filters:
            - AddResponseHeader=Access-Control-Allow-Origin, http://localhost:8085
            - AddResponseHeader=Access-Control-Allow-Methods, GET, POST, PUT, DELETE, OPTIONS
            - AddResponseHeader=Access-Control-Allow-Headers, Content-Type, Authorization
            - AddRequestHeader=Access-Control-Allow-Origin, http://localhost:8085

jwt:
  secret: MiClaveSecretaSuperLargaYSeguraQueTieneAlMenos512BitsDeLongitud

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
