server:
  port: 8086  # Puerto del API Gateway

spring:
  application:
    name: ms-api-gateway

  cloud:
    gateway:
      routes:
      
        - id: ms-usuarios
          uri: http://localhost:8081
          predicates:
            - Path=/api/permissions/**, /api/roles/**, /api/userroles/**, /api/rolespermisos/**, /api/usuarios/**, /api/auth/**

        - id: ms-productos
          uri: http://localhost:8082
          predicates:
            - Path=/api/productos/**, /api/claves/**, /api/valores/**, /api/clavevalorrelacion/**

        - id: ms-categorias
          uri: http://localhost:8083
          predicates:
            - Path=/api/categorias/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://192.168.1.101:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

  main:
    web-application-type: reactive

jwt:
  secret: MiClaveSecretaSuperLargaYSeguraQueTieneAlMenos512BitsDeLongitud

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
