server:
  port: 0

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: ms-productos
          uri: http://localhost:8082
          predicates:
            - Path=/api/productos/**, /api/categorias/**

        - id: ms-usuarios
          uri: http://localhost:8081
          predicates:
            - Path= /api/permissions/**, /api/roles/**, /api/userroles/**, /api/rolespermisos/**, /api/usuarios/**

jwt:
  secret: MiClaveSecretaSuperLargaYSeguraQueTieneAlMenos512BitsDeLongitud

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

