server:
  port: 8085  # Se puede dejar en 0 si usas puertos dinámicos o lo defines en bootstrap.yml

spring:
  application:
    name: ms-auth

  datasource:
    url: jdbc:oracle:thin:@localhost:1522/free
    username: C##auth
    password: auth123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
