server:
  port: 8086  # Puerto del API Gateway

spring:
  application:
    name: ms-api-gateway

  cloud:
    gateway:
      routes:
        - id: ms-auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**

        - id: ms-usuarios
          uri: http://localhost:8082
          predicates:
            - Path=/api/usuarios/**

        - id: ms-setperms
          uri: http://localhost:8083
          predicates:
            - Path=/api/permissions/**, /api/roles/**, /api/userroles/**, /api/rolespermisos/**

        - id: ms-productos
          uri: http://localhost:8084
          predicates:
            - Path=/api/productos/**

        - id: ms-categorias
          uri: http://localhost:8085
          predicates:
            - Path=/api/categorias/**

  main:
    web-application-type: reactive

jwt:
  secret: MiClaveSecretaSuperLargaYSeguraQueTieneAlMenos512BitsDeLongitud

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
