server:
  port: 8084

spring:
  application:
    name: ms-api-gateway

  cloud:
    gateway:
      routes:
        - id: ms-productos
          uri: http://localhost:8082
          predicates:
            - Path=/api/productos/**, /api/categorias/**

        - id: ms-usuarios
          uri: http://localhost:8081
          predicates:
            - Path=/api/permissions/**, /api/roles/**, /api/userroles/**, /api/rolespermisos/**, /api/usuarios/**

        - id: ms-categorias
          uri: http://localhost:8083
          predicates:
            - Path=/api/categorias/**

jwt:
  secret: MiClaveSecretaSuperLargaYSeguraQueTieneAlMenos512BitsDeLongitud

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
