server:
  address: 0.0.0.0
  port: 8084  # Puedes cambiar el puerto si deseas

spring:
  application:
    name: ms-carrito

  datasource:
    url: jdbc:oracle:thin:@26.246.241.197:1525/free
    username: C##carrito
    password: carrito123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
