server:
  port: 8081

spring:
  application:
    name: ms-usuarios

  datasource:
    url: jdbc:oracle:thin:@localhost:1522/free
    username: C##usuarios
    password: usuarios123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.hostinger.com
    port: 465
    username: TU_CORREO@proactivoweb.com   # ← Pon aquí tu correo real
    password: TU_CONTRASEÑA_DE_HOSTINGER   # ← La contraseña que pusiste al crearlo
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: MS-USUARIOS
    description: Microservicio de usuarios
    version: 1.0.0

jwt:
  secret: "MiClaveSecretaSuperLargaYSeguraQueTieneAlMenos512BitsDeLongitud"

app:
  owner:
    token: "nosewey"
